ecommerceproject/ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views


app_name = 'cart'

urlpatterns = [
    path("add_to_cart/<int:p>/", views.add_to_cart, name='add_to_cart'),
    path('cartview', views.cartview, name='cartview'),
    path('cart_remove/<int:p>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:k>/', views.full_remove, name='full_remove'),
    path('checkout', views.cart_checkout, name='checkout'),

    path("initiate_payment/", views.initiate_payment, name="initiate_payment"),
    path("payment-success/", views.payment_success, name="payment_success"),
    path("payment-failed/", views.payment_failed, name="payment_failed"),
  

]
# path('order_details',views.order_details,name='order_details'),

ecommerceproject/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
    path('auth/', include('social_django.urls', namespace='social')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerceproject/ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path,include
from search import views
app_name = 'search'

urlpatterns = [
    path('',views.searchresults,name='searchresults')


]

ecommerceproject/ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views

app_name = 'shop'

urlpatterns = [
    path("", views.home, name='home'),
    path('products', views.all_products, name='allproducts'),
    path('all_products_page2', views.all_products_page2, name='all_products_page2'),
    path('prodetails/<p>/', views.pro_details, name='prodetails'),
    path('prodetails/<k>/', views.pro_details, name='color_change'),
    path('signup', views.sign_up, name='signup'),
    path('login', views.log_in, name='login'),
    path('profile_view',views.profile_view,name='profile_view'),
    path('logout', views.user_logout, name='logout')

]

ecommerceproject/ecommerce/cart/models.py
from django.db import models
from shop.models import Products
from django.contrib.auth.models import User



class Cart(models.Model):
    cart_products = models.ForeignKey(Products, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    quantity = models.IntegerField()
    data_added = models.DateField(auto_now_add=True)

    def subtotal(self):
        return self.quantity * self.cart_products.price

    def __str__(self):
        return self.cart_products.name

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    address = models.TextField(null=True,blank=True)
    phone = models.IntegerField(null=True,blank=True)
    alternate_mobile_num = models.IntegerField(null=True,blank=True)
    order_status = models.CharField(max_length=30, default='pending',null=True,blank=True)
    delivery_status = models.CharField(max_length=30, default='pending',null=True,blank=True)
    no_of_items = models.IntegerField(default=0,null=True,blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    ordered_products = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def subtotal(self):
        return self.quantity * self.product.price

    def __str__(self):
        return self.order.user.username

ecommerceproject/ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerceproject/ecommerce/cart/views.py
from django.shortcuts import render, redirect
from shop.models import Products
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from cart.models import Cart, Order , OrderItem

import razorpay
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseServerError
import requests


@login_required
def cartview(request):
    total = 0
    user = request.user
    try:
        cart = Cart.objects.filter(user=user)
        for i in cart:
            total += i.quantity * i.cart_products.price

    except Cart.DoesNotExist:
        pass
    cart = Cart.objects.filter(user=user)
    return render(request, 'cartview.html', {'cart': cart, 'total': total})


@login_required
def add_to_cart(request, p):
    p = Products.objects.get(id=p)
    user = request.user
    try:
        cart = Cart.objects.get(user=user, cart_products=p)
        if (cart.quantity < cart.cart_products.stock):
            cart.quantity += 1
        cart.save()
    except Cart.DoesNotExist:
        cart = Cart.objects.create(user=user, cart_products=p, quantity=1)
        cart.save()

    return redirect('cart:cartview')


# def add_to_cart(request, p):
#     k = Cart.objects.get(id=p)
#     k.quantity += 1
#     k.save()
#     return redirect('cart:cartview')

# def cart_remove(request, p):
#     k = Cart.objects.get(id=p)
#     k.quantity -= 1
#     k.save()
#     return redirect('cart:cartview')


@login_required
def cart_remove(request, p):
    p = Products.objects.get(id=p)
    user = request.user
    try:
        cart = Cart.objects.get(user=user, cart_products=p)
        if (cart.quantity > 1):
            cart.quantity -= 1
            cart.save()
        else:
            cart.delete()
    except Cart.DoesNotExist:
        pass

    return redirect('cart:cartview')


@login_required
def full_remove(request, k):
    p = Products.objects.get(id=k)
    user = request.user
    try:
        cart = Cart.objects.get(user=user, cart_products=p)
        cart.delete()
    except Cart.DoesNotExist:
        pass
    return redirect('cart:cartview')



def cart_checkout(request):
     try:
        previous_order = Order.objects.filter(user=request.user).first()
        if previous_order:
                # Fetch previously entered order details
            address = previous_order.address
            phone = previous_order.phone

        if request.method == 'POST':
            address = request.POST['address']
            phone = request.POST['phone']
            if not address or not phone:
                error_message = "Please provide both address and phone number."
                return render(request, 'checkout.html', {'error_message': error_message})
            
            if previous_order:
                # Update existing order details
                previous_order.address = address
                previous_order.phone = phone
                previous_order.save()
            else:
                user_order = Order.objects.create(user=request.user, address=address, phone=phone)
                user_ordered_products = Cart.objects.filter(user=request.user)
                total_items = 0
                
                for cart_item in user_ordered_products:
                    order_item = OrderItem.objects.create(order=user_order,ordered_products=cart_item.cart_products,quantity=cart_item.quantity)
                    total_items += cart_item.quantity
                
                # Update the order with the total number of items
                user_order.no_of_items = total_items
                user_order.save()
            return initiate_payment(request)
        else:          
            if not previous_order:
                address = ''
                phone = ''        
            total = 0
            cart_items = Cart.objects.filter(user=request.user)
            for items in cart_items:
              total += items.subtotal()
       
            return render(request, 'checkout.html', {'cart':  cart_items, 'total': total,'address': address, 'phone': phone})
     except requests.exceptions.RequestException as e:
         error_message = "Internet connection error occurred. Please check your internet connection and try again."
         return render(request, 'error.html', {'error_message': error_message})

 



# payment_app/views.py
@login_required
def initiate_payment(request):
    total = 0
    user_cart = Cart.objects.filter(user=request.user)
    for i in user_cart:
        total += i.quantity * i. cart_products.price

    amount = float(total) * 100  # Amount in paise
    client = razorpay.Client(auth=(settings.KEY, settings.SECRET))

    payment_data = {
            "amount": amount,
            "currency": "INR",
            "receipt": "order_receipt01",
          }

    order = client.order.create(data=payment_data)
    
        # Include key, name, description, and image in the JSON response
    response_data = {
            "id": order["id"],
            "amount": int(order["amount"])/100,
            "currency": order["currency"],
            "key": settings.KEY,
            "name": "ASHION",
            "description": "Payment for Your Product",
            "image": "https://www.onlinelogomaker.com/blog/wp-content/uploads/2017/06/shopping-online.jpg",  # Replace with your logo URL
        }
  
    user_order_details = Order.objects.get(user=request.user)
    return render(request, "payment.html",{'data':response_data,'user_order_details':user_order_details})


@csrf_exempt
def payment_success(request):
    user_current_cart_items = Cart.objects.filter(user=request.user) 
    user_current_cart_items.delete()
    return render(request, "payment_success.html")
@csrf_exempt
def payment_failed(request):
    return render(request, "payment_failed.html")



















# @login_required
# def checkout(request):
#     # total = 0
#     # if (request.method == 'POST'):
#     #     a = request.POST['a']
#     #     p = request.POST['p']
#     #     n = request.POST['n']
#     #     user = request.user
#     #     cart = Cart.objects.filter(user=user)
#     #     for i in cart:
#     #         total += i.quantity * i.product.price
#     #         ac = Account.objects.get(acc_number=n)
#     #         if (ac.amount >= total):
#     #             ac.amount = ac.amount - total
#     #             ac.save()
#     #             for i in cart:
#     #                 o = Order.objects.create(user=user, products=i.product, address=a, phone=p, order_status='paid',
#     #                                          no_of_items=i.quantity)
#     #                 o.save()
#     #                 i.product.stock = i.product.stock - i.quantity
#     #                 i.product.save()
#     #             cart.delete()
#     #             msg = 'Order Placed Successfully'
#     #             return render(request, 'callback.html', {'msg': msg})
#     #         else:
#     #             msg = 'Insufficient amount,You cannot place order'
#     #             return render(request, 'callback.html', {'msg': msg})
#     cart = Cart.objects.all()
#     return render(request, 'checkout.html', {'cart': cart})

ecommerceproject/ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Products
from django.db.models import Q


def searchresults(request):
    query = ""
    products = None
    if (request.method == 'POST'):
        query = request.POST['q']
        print(query)
        if (query):
            products = Products.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'search.html', {'products': products, 'query': query})

ecommerceproject/ecommerce/templates/cartview.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {% endblock %}
{% block content %}


<!-- Breadcrumb Begin -->
<div class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__links">
                    <a href="./index.html"><i class="fa fa-home"></i> Home</a>
                    <span>Shopping cart</span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- Shop Cart Section Begin -->


<section class="shop-cart spad">
    <div class="container">
        {% if not cart %}
        <div>
            <h1 class="text-center">Cart is empty</h1>
            <a href="{% url 'shop:home' %}">Continue shopping</a>
        </div>

        {% else %}
        <div class="row">
            <div class="col-lg-12">
                <div class="shop__cart__table">
                    <table>
                        <thead>
                        <tr>
                            <th>Product</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for i in cart %}
                        <tr>
                            <td class="cart__product__item">
                                <img src="{{i.cart_products.image.url}}" style="height:250px;width:200px;" alt="">
                                <div class="cart__product__item__title">
                                    <h6>{{i.cart_products.name}}</h6>
                                    <div class="rating">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                    </div>
                                </div>
                            </td>
                            <td class="cart__price">{{i.cart_products.price}}</td>
                            <td>
                                <a href="{% url 'cart:cart_remove' i.cart_products.id %}"><i class="fa-solid fa-circle-minus"
                                                                      style="color:black"></i></a>
                                <span>   {{i.quantity}} </span>

                                <a href="{% url 'cart:add_to_cart' i.cart_products.id %}"><i class="fa-solid fa-circle-plus"
                                                                       style="color:black"></i></a>

                            </td>
                            <td class="cart__total">{{i.subtotal}}</td>
                            <td class="cart__close"><a href="{% url 'cart:full_remove' i.cart_products.id %}" class="icon_close"></a></td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="cart__btn">
                    <a href="{% url 'shop:allproducts' %}">Continue Shopping</a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="cart__btn update__btn">
                    <a href="{% url 'shop:all_products_page2' %}"><span class="icon_loading"></span> Update cart</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="discount__content">
                    <h6>Discount codes</h6>
                    <form action="#">
                        <input type="text" placeholder="Enter your coupon code">
                        <button type="submit" class="site-btn">Apply</button>
                    </form>
                </div>
            </div>
            <div class="col-lg-4 offset-lg-2 container p-4 mb-4" style="height:150px">
                <div class="cart__total__procced row">
                    <div class="col-md-12"><h6>Cart total</h6></div>
                    <div class="col-md-6">Subtotal</div>
                    <div class="col-md-6">
                        {% for i in cart %}
                            <div>{{i.subtotal}}</div>
                        {% endfor %}
                        </div>
                        <div class="col-md-6 mt-2">Total</div>
                    <div class="col-md-6 mt-2">{{total}}</div>
                    <div class="mt-4">
                        <a href="{% url 'cart:checkout' %}" class="primary-btn" style="width:250px">Proceed to checkout</a>
                    </div>

                </div>
            </div>
        </div>
        {% endif %}
    </div>
</section>
<!-- Shop Cart Section End -->

<!-- Instagram Begin -->
<div class="instagram mt-4">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="{% static 'img/instagram/insta-1.jpg' %}">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#">@ ashion_shop</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="{% static 'img/instagram/insta-2.jpg' %}">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#">@ ashion_shop</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="{% static 'img/instagram/insta-3.jpg' %}">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#">@ ashion_shop</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="{% static 'img/instagram/insta-4.jpg' %}">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#">@ ashion_shop</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="{% static 'img/instagram/insta-5.jpg' %}">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#">@ ashion_shop</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="{% static 'img/instagram/insta-6.jpg' %}">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#">@ ashion_shop</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Instagram End -->

{% endblock %}

<!--{% if not cart %}-->
<!--<div>-->
<!--    <h1 class="text-center">Cart is empty</h1>-->
<!--    <a href="{% url 'shop:allprodcat' %}">Continue shopping</a>-->
<!--</div>-->

<!--{% else %}-->
<!--<div class="row" style="margin-bottom:100px">-->
<!--    <h2 CLASS="text-center">SHOPPING CART</h2>-->
<!--    <div class="col-sm-8">-->
<!--        <table class="table table-bordered">-->
<!--            <tr>-->
<!--                <th colspan="5" CLASS="text-center">CART ITEM</th>-->
<!--            </tr>-->
<!--            {% for i in cart %}-->
<!--            <tr>-->
<!--                <td><img src="{{i.product.image.url}}" height="100px" width="100px"></td>-->
<!--                <td><P><strong>{{i.product.name}}</strong></P></td>-->
<!--                <td><p><strong>Product Id:{{i.product.id}}</strong></p>-->
<!--                    <p><strong>Unit price:{{i.product.price}}</strong></p>-->
<!--                    <p><strong>Quantity:{{i.quantity}}*{{i.product.price}}</strong></p>-->
<!--                    <p>Subtotal:{{i.subtotal}}</p>-->
<!--                <td>-->
<!--                    {% if i.quantity < i.product.stock %}-->
<!--                    <a href="{% url 'cart:add_to_cart' i.product.id %}"><i class="fa-solid fa-circle-plus "-->
<!--                                                                           style="color:black"></i></a>-->
<!--                    <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-circle-minus"-->
<!--                                                                           style="color:black"></i></a>-->
<!--                    <a href="{% url 'cart:full_remove' i.product.id %}"><i class="fa-solid fa-trash-can"-->
<!--                                                                           style="color:black"></i></a>-->
<!--                    {% else %}-->
<!--                    <a href="{% url 'cart:add_to_cart' i.product.id %}"><i class="fa-solid fa-circle-minus "-->
<!--                                                                           style="color:black"></i></a>-->
<!--                    <a href="{% url 'cart:full_remove' i.product.id %}"><i class="fa-solid fa-trash-can "-->
<!--                                                                           style="color:black"></i></a>-->
<!--                    {% endif %}-->
<!--                </td>-->
<!--            </tr>-->
<!--            {% endfor %}-->
<!--        </table>-->
<!--    </div>-->
<!--    <div class="col-sm-3">-->
<!--        <table class="table table-bordered">-->
<!--            <tr>-->
<!--                <th class="colspan=5">CHECK OUT</th>-->
<!--            </tr>-->
<!--            <tr class="text-center">-->
<!--                <td>TOTAL AMOUNT: {{total}}</td>-->
<!--            </tr>-->
<!--        </table>-->

<!--            <a href="{% url 'cart:orderform' %}" class="btn btn-primary">Place order</a>-->
<!--            <a href="{% url 'shop:allprodcat' %}"  class="btn btn-success ms-5">Continue-->
<!--                shopping</a>-->
<!--    </div>-->
<!--</div>-->
<!--{% endif %}-->

ecommerceproject/ecommerce/templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<!-- Breadcrumb Begin -->
<div class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__links">
                    <a href="./index.html"><i class="fa fa-home"></i> Home</a>
                    <span>Shopping cart</span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->

<!-- Checkout Section Begin -->
<section class="checkout spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h6 class="coupon__link"><span class="icon_tag_alt"></span> <a href="#">Have a coupon?</a> Click
                    here to enter your code.</h6>
            </div>
        </div>
        <div  class="checkout__form">
            <div class="row">
                <div class="col-lg-8">
                    <H2>Login: {{user.email}} </H2>
                    <form method="POST" action="{% url 'cart:checkout' %}" >
                        <!-- <form method="POST"> -->
                        {% csrf_token %}
                        <h4>Enter the Address you want to deliver</h4>
                        <div class="mb-3">
                            <label class="form-label">ADDRESS</label>
                            <input type="text" class="form-control" name="address" value="{{address}}">
                        </div>

                        <div class="mb-3">
                            <label class="form-label"> PHONE NUMBER</label>
                            <input type="number" class="form-control" name="phone" value="{{phone}}">
                        </div>

                        <button type="submit" class="btn btn-primary">Continue to pay</button>
                        <!-- <a type="submit" href="{% url 'cart:checkout' %}" class="btn btn-primary">Continue to pay</a> -->
                    </form>
                    <br>
                    <strong>{{error_message}}</strong>

                </div>
                <div class="col-lg-4">
                    <div class="checkout__order">
                        <h5>Your order</h5>
                        <div class="checkout__order__product">
                            <table style="width:350px">
                                <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th>Subtotal</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for i in cart %}
                                    <tr>
                                        <td class="cart__product__item__title">
                                            <h6>{{i.cart_products.name}} x {{i.quantity}}</h6>
                                        </td>
                                        <td class="cart__price">{{i.subtotal}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>

                            <div class="checkout__order__total">
                                <ul>
                                    <li>Total <span>{{total}}</span></li>
                                </ul>
                            </div>
                            <div class="checkout__order__widget">

                                <p>Create am acount by entering the information below. If you are a returing
                                    customer
                                    login at the top of the page.</p>

                            </div>
                            <!-- <button style="
                               margin-left: 41px;
                               display: flex;
                               align-items: center;
                               justify-content: center;
                               width: 230px;
                               height: 50px;
                               background-color: rgb(183, 46, 46);                                                    
                               border-radius: 30px;
                               ">
                                       <a style="color: white;font-weight: bold;" href="{% url 'cart:initiate_payment' %}" >Place order</a>
                               </button> -->
                        </div>
                    </div>
                </div>
        </form>
    </div>
</section>
<!-- Checkout Section End -->

<!-- Instagram Begin -->
<div class="instagram">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="{% static 'img/instagram/insta-1.jpg' %}">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#">@ ashion_shop</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="{% static 'img/instagram/insta-2.jpg' %}">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#">@ ashion_shop</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="{% static 'img/instagram/insta-3.jpg' %}">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#">@ ashion_shop</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="{% static 'img/instagram/insta-4.jpg' %}">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#">@ ashion_shop</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="{% static 'img/instagram/insta-5.jpg' %}">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#">@ ashion_shop</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4 p-0">
                <div class="instagram__item set-bg" data-setbg="{% static 'img/instagram/insta-6.jpg' %}">
                    <div class="instagram__text">
                        <i class="fa fa-instagram"></i>
                        <a href="#">@ ashion_shop</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Instagram End -->

{% endblock %}


<!--<div class="container" >-->
<!--    < method="POST">-->
<!--        {% csrf_token %}-->
<!--        <div class="mb-3">-->
<!--            <label class="form-label">Address</label>-->
<!--            <input type="text" class="form-control" name="a" placeholder="enter address">-->

<!--            <div class="mb-3">-->
<!--                <label class="form-label">Phone</label>-->
<!--                <input type="text" class="form-control" name="p" placeholder="enter phone">-->
<!--            </div>-->
<!--            <div class="mb-3">-->
<!--                <label class="form-label">Accountno</label>-->
<!--                <input type="text" class="form-control" name="n" placeholder="enter account no">-->
<!--            </div>-->
<!--           <input type="submit" class="btn btn-primary form-control">-->
<!--        </div>-->
<!--    </form>-->

<!--</div>-->

ecommerceproject/ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div>
        <h4> you have searced for<span class="text-success"> {{query}}</span> </h4>
    </div>
</center>

<div class="container-fluid " style="margin-bottom:100px">
  <div class="row ms-4">
    {% for i in products %}
    <div class="col-sm-4">
     <div class="card" style="width: 25rem;height:600px">
      <img src="{{ i.image.url }}"  style="height:280px;" class="card-img-top" alt="...">
      <div class="card-body">
      <h5 class="card-title text-center">{{ i.name }}</h5>
      <p class="card-text text-center" style="text-align:justify">{{i.price}}</p>
      <a href="{% url 'shop:prodetails' i.slug %}" style="position:relative;left:35%" class="btn btn-primary">DETAILS</a>
      </div>
     </div>
    </div>
      {% empty %}
      <h6 class="text-center text-danger">0 Results Found</h6>

       {% endfor %}
  </div>

</div>
{% endblock %}